BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ERRORCODES';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE TABLE ERRORCODES
(
  ERROR_CODE            NUMBER NOT NULL ENABLE, 
  DESCRIPTION           VARCHAR2(3000), 
  CREATE_DTM            DATE, 
  LAST_UPDATE_DTM       DATE, 
  PRIMARY KEY (ERROR_CODE)
)
TABLESPACE &TABLESPACE;
/

COMMENT ON TABLE ERRORCODES IS 'Customized errors configuration table';

COMMENT ON COLUMN ERRORCODES.ERROR_CODE IS 'Customized error code';
COMMENT ON COLUMN ERRORCODES.DESCRIPTION IS 'Error description';
COMMENT ON COLUMN ERRORCODES.CREATE_DTM IS 'Insert date';
COMMENT ON COLUMN ERRORCODES.LAST_UPDATE_DTM IS 'Last update date';
