BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PARAMS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE TABLE PARAMS
(
  PARAM                 VARCHAR2(255) NOT NULL ENABLE, 
  VALUE                 VARCHAR2(255) NOT NULL ENABLE, 
  START_DTM             DATE NOT NULL ENABLE, 
  END_DTM               DATE DEFAULT NULL,
  DESCRIPTION           VARCHAR2(255) DEFAULT NULL,
  PRIMARY KEY (PARAM, START_DTM)
)
TABLESPACE &TABLESPACE;
/

COMMENT ON TABLE PARAMS IS 'Configuration table';

COMMENT ON COLUMN PARAMS.PARAM IS 'Parameter logical name';
COMMENT ON COLUMN PARAMS.VALUE IS 'Parameter value';
COMMENT ON COLUMN PARAMS.START_DTM IS 'Date from which the parameter is valid';
COMMENT ON COLUMN PARAMS.END_DTM IS 'Date from which the parameter becomes invalid';
COMMENT ON COLUMN PARAMS.DESCRIPTION IS 'Parameter description';
